kind: Service
apiVersion: v1
metadata:
  name: $APP_NAME
  namespace: $KUBE_NAMESPACE
  labels:
    app: $APP_NAME
  annotations:
    kubesphere.io/description: $APP_DESC
spec:
  ports:
    - name: http-82
      protocol: TCP
      port: 82
      targetPort: 82
  selector:
    app: $APP_NAME
  type: NodePort
  sessionAffinity: None
  externalTrafficPolicy: Cluster
